/*
 * This source file was generated by the Gradle 'init' task
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-gradle-gradle-app using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929

ROOST_METHOD_HASH=get_0d973ea47e
ROOST_METHOD_SIG_HASH=get_c2afb2c160

Scenario 1: Get element at index 0 from a list with one element

Details:
  TestName: getElementAtIndexZeroFromSingleElementList
  Description: This test verifies that the get method correctly retrieves the first element (at index 0) from a LinkedList containing exactly one element. This is a basic positive test case that validates the method works for the simplest non-empty list scenario.
Execution:
  Arrange: Create a new LinkedList instance and add one element (e.g., "first") to it using the add method.
  Act: Call the get method with index 0.
  Assert: Use assertEquals to verify that the returned String matches the element that was added ("first").
Validation:
  The assertion verifies that the get method can successfully retrieve the head element when the list contains only one node. This is fundamental functionality as index 0 should always return the head node's data when the list is not empty. This test ensures the method correctly handles the base case of a single-element list without traversing beyond the head.

---

Scenario 2: Get element at index 0 from a list with multiple elements

Details:
  TestName: getElementAtIndexZeroFromMultipleElementList
  Description: This test checks that the get method returns the first element when multiple elements exist in the list. It validates that the method correctly identifies the head node without being affected by subsequent nodes.
Execution:
  Arrange: Create a LinkedList and add multiple elements (e.g., "first", "second", "third") using the add method.
  Act: Invoke the get method with index 0.
  Assert: Use assertEquals to confirm the returned value is "first".
Validation:
  This assertion ensures that when index is 0, the while loop in the get method does not execute (since index > 0 is false), and the method directly returns the head node's data. This is critical for verifying that the method doesn't incorrectly traverse the list when it should return the first element immediately.

---

Scenario 3: Get element at the last valid index in a list

Details:
  TestName: getElementAtLastValidIndex
  Description: This test validates that the get method can successfully retrieve the last element in the LinkedList by using the highest valid index (size - 1). This tests the boundary condition at the end of the list.
Execution:
  Arrange: Create a LinkedList and add three elements (e.g., "first", "second", "third"). Calculate the last index as size() - 1, which should be 2.
  Act: Call the get method with index 2.
  Assert: Use assertEquals to verify the returned String is "third".
Validation:
  This test confirms that the get method correctly traverses through all nodes until reaching the last element. The while loop should decrement index from 2 to 0 while moving the iterator from head through two next references. This validates proper traversal logic and ensures the method can access elements at the end of the list without throwing an exception.

---

Scenario 4: Get element at a middle index in a list

Details:
  TestName: getElementAtMiddleIndex
  Description: This test ensures the get method correctly retrieves an element from the middle of the LinkedList, validating the traversal logic for arbitrary valid indices.
Execution:
  Arrange: Create a LinkedList and add five elements (e.g., "first", "second", "third", "fourth", "fifth").
  Act: Invoke the get method with index 2 (middle element).
  Assert: Use assertEquals to verify the returned value is "third".
Validation:
  This assertion verifies that the get method's while loop correctly decrements the index counter while advancing the iterator through the linked nodes. Starting from head, the iterator should move twice (index 2 to 1 to 0) to reach the third node. This test is important for confirming the method works correctly for any valid index, not just boundary cases.

---

Scenario 5: Get element throws IndexOutOfBoundsException when index equals list size

Details:
  TestName: getThrowsExceptionWhenIndexEqualsSize
  Description: This test verifies that the get method throws an IndexOutOfBoundsException when the provided index equals the size of the list, which is one position beyond the last valid index.
Execution:
  Arrange: Create a LinkedList and add three elements. The valid indices are 0, 1, 2, so index 3 (equal to size) is invalid.
  Act: Call the get method with index 3.
  Assert: Use assertThrows with IndexOutOfBoundsException.class to verify the exception is thrown.
Validation:
  This test ensures proper error handling for the boundary condition where the index is exactly one past the last valid position. When index equals the size, the while loop will traverse all nodes until it becomes null, and the subsequent null check should trigger the IndexOutOfBoundsException. This is crucial for preventing null pointer exceptions and providing clear error messages to users.

---

Scenario 6: Get element throws IndexOutOfBoundsException when index is greater than list size

Details:
  TestName: getThrowsExceptionWhenIndexExceedsSize
  Description: This test checks that the get method throws an IndexOutOfBoundsException when the index is significantly larger than the list size, validating error handling for clearly invalid indices.
Execution:
  Arrange: Create a LinkedList with two elements, making valid indices 0 and 1.
  Act: Invoke the get method with index 10 (much larger than size).
  Assert: Use assertThrows to verify IndexOutOfBoundsException is thrown.
Validation:
  This assertion confirms that the method properly handles cases where the requested index far exceeds the list bounds. The while loop will continue until it becomes null (after traversing all nodes), and the null check will throw the appropriate exception. This test is important for robustness, ensuring the method fails gracefully with a meaningful exception rather than causing undefined behavior.

---

Scenario 7: Get element throws IndexOutOfBoundsException when list is empty and index is 0

Details:
  TestName: getThrowsExceptionWhenListIsEmptyAndIndexIsZero
  Description: This test verifies that attempting to get an element at index 0 from an empty LinkedList (where head is null) throws an IndexOutOfBoundsException.
Execution:
  Arrange: Create a new LinkedList without adding any elements, ensuring head remains null.
  Act: Call the get method with index 0.
  Assert: Use assertThrows to verify IndexOutOfBoundsException is thrown with the message "Index is out of range".
Validation:
  This test validates the edge case of an empty list. Since head is null, the iterator it starts as null, the while loop condition (index > 0 && it != null) is false (because it is null), and the subsequent null check immediately throws the exception. This is critical for preventing null pointer exceptions and ensuring the method communicates clearly that the list has no elements to retrieve.

---

Scenario 8: Get element throws IndexOutOfBoundsException when list is empty and index is positive

Details:
  TestName: getThrowsExceptionWhenListIsEmptyAndIndexIsPositive
  Description: This test ensures that the get method throws an IndexOutOfBoundsException when attempting to access any positive index in an empty LinkedList.
Execution:
  Arrange: Create a LinkedList instance without adding any elements.
  Act: Invoke the get method with index 5.
  Assert: Use assertThrows to verify IndexOutOfBoundsException is thrown.
Validation:
  This assertion confirms proper error handling when the list is empty and a positive index is requested. With head being null, the iterator starts as null, the while loop doesn't execute (due to the it != null condition), and the null check throws the exception. This test ensures consistent behavior regardless of the index value when the list is empty.

---

Scenario 9: Get element throws IndexOutOfBoundsException with negative index

Details:
  TestName: getThrowsExceptionWithNegativeIndex
  Description: This test verifies the behavior of the get method when a negative index is provided, which should result in an IndexOutOfBoundsException.
Execution:
  Arrange: Create a LinkedList and add two elements (e.g., "first", "second").
  Act: Call the get method with index -1.
  Assert: Use assertThrows to verify IndexOutOfBoundsException is thrown.
Validation:
  This test validates error handling for invalid negative indices. Since the while loop condition checks (index > 0), a negative index will not cause the loop to execute, and the method will attempt to return head.data. If the list is not empty, it would return the head element, which is incorrect behavior. However, the test documents the current implementation's behavior with negative indices. Note: The current implementation has a bug where negative indices return the head element instead of throwing an exception, but this test verifies the expected exception should be thrown.

---

Scenario 10: Get multiple elements sequentially from the same list

Details:
  TestName: getMultipleElementsSequentially
  Description: This test verifies that the get method can be called multiple times on the same LinkedList instance with different indices, and each call returns the correct element without side effects.
Execution:
  Arrange: Create a LinkedList and add four elements (e.g., "alpha", "beta", "gamma", "delta").
  Act: Call the get method multiple times with indices 0, 1, 2, and 3 in sequence.
  Assert: Use assertEquals for each call to verify the returned values are "alpha", "beta", "gamma", and "delta" respectively.
Validation:
  This test ensures that the get method is idempotent and doesn't modify the list state. Each invocation should start fresh from the head and traverse independently. This is important for confirming that the method doesn't have unintended side effects like modifying the head reference or node connections, which would affect subsequent calls.

---

Scenario 11: Get element after adding and removing elements

Details:
  TestName: getElementAfterAddAndRemoveOperations
  Description: This test validates that the get method works correctly after the LinkedList has been modified through add and remove operations, ensuring the method reflects the current state of the list.
Execution:
  Arrange: Create a LinkedList, add three elements ("first", "second", "third"), then remove the middle element ("second") using the remove method.
  Act: Call the get method with index 1.
  Assert: Use assertEquals to verify the returned value is "third" (which is now at index 1 after removal).
Validation:
  This assertion confirms that the get method operates on the current state of the LinkedList after modifications. After removing "second", the list should contain ["first", "third"], so index 1 should return "third". This test is crucial for ensuring the get method correctly traverses the modified linked structure and doesn't rely on stale references or cached data.

---

Scenario 12: Get element verifies correct traversal count

Details:
  TestName: getElementVerifiesCorrectTraversalCount
  Description: This test ensures that the get method traverses exactly the required number of nodes to reach the specified index, neither more nor less.
Execution:
  Arrange: Create a LinkedList with six elements (e.g., "zero", "one", "two", "three", "four", "five").
  Act: Invoke the get method with index 3.
  Assert: Use assertEquals to verify the returned value is "three".
Validation:
  This test validates the precision of the traversal logic. The while loop should execute exactly 3 times (decrementing index from 3 to 2 to 1 to 0) while moving the iterator through 3 next references. This ensures the method doesn't over-traverse or under-traverse, which could return incorrect elements or cause exceptions. The test confirms the tight coupling between the index parameter and the number of node traversals.

---

Scenario 13: Get element from list with single element at invalid index 1

Details:
  TestName: getThrowsExceptionFromSingleElementListAtIndexOne
  Description: This test verifies that attempting to access index 1 in a LinkedList containing only one element (valid index is only 0) throws an IndexOutOfBoundsException.
Execution:
  Arrange: Create a LinkedList and add only one element (e.g., "only").
  Act: Call the get method with index 1.
  Assert: Use assertThrows to verify IndexOutOfBoundsException is thrown.
Validation:
  This assertion ensures proper boundary checking for single-element lists. With only one node, the valid index is 0. When index 1 is provided, the while loop executes once (index > 0 is true), moving it to it.next which is null, then decrementing index to 0. The null check then triggers the exception. This test is important for validating that the method correctly identifies when an index exceeds the list bounds, even by just one position.

---

Scenario 14: Get element returns correct data type

Details:
  TestName: getElementReturnsStringType
  Description: This test confirms that the get method returns a String type as declared in its signature, and the returned value can be used as a String object.
Execution:
  Arrange: Create a LinkedList and add an element with a specific string value (e.g., "testString").
  Act: Invoke the get method with index 0 and store the result in a String variable.
  Assert: Use assertNotNull to verify the returned value is not null, and use assertEquals to confirm it matches the expected string value.
Validation:
  This test validates the return type contract of the get method. Since Node.data is declared as final String, the method should always return a valid String reference (or throw an exception). This test ensures type safety and confirms that the returned data can be used in string operations without casting or type checking. It's fundamental for API contract verification.

---

Scenario 15: Get element with index at boundary between valid and invalid

Details:
  TestName: getElementAtBoundaryBetweenValidAndInvalid
  Description: This test examines the precise boundary between the last valid index and the first invalid index to ensure the get method correctly distinguishes between them.
Execution:
  Arrange: Create a LinkedList with exactly four elements. The last valid index is 3, and the first invalid index is 4.
  Act: First call get with index 3 (valid), then call get with index 4 (invalid).
  Assert: Use assertEquals to verify index 3 returns the correct element, and use assertThrows to verify index 4 throws IndexOutOfBoundsException.
Validation:
  This test validates the critical boundary condition where valid indices end and invalid indices begin. At index 3, the while loop should traverse to the last node and return its data successfully. At index 4, the traversal should reach null, triggering the exception. This test is essential for confirming the method's boundary detection logic is precise and doesn't have off-by-one errors.

*/

// ********RoostGPT********

package org.example.list;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;

public class LinkedListGetTest {
    
    private LinkedList linkedList;
    
    @BeforeEach
    public void setUp() {
        linkedList = new LinkedList();
    }
    
    @Test
    @Tag("valid")
    public void getElementAtIndexZeroFromSingleElementList() {
        linkedList.add("first");
        String result = linkedList.get(0);
        assertEquals("first", result);
    }
    
    @Test
    @Tag("valid")
    public void getElementAtIndexZeroFromMultipleElementList() {
        linkedList.add("first");
        linkedList.add("second");
        linkedList.add("third");
        String result = linkedList.get(0);
        assertEquals("first", result);
    }
    
    @Test
    @Tag("boundary")
    public void getElementAtLastValidIndex() {
        linkedList.add("first");
        linkedList.add("second");
        linkedList.add("third");
        int lastIndex = linkedList.size() - 1;
        String result = linkedList.get(lastIndex);
        assertEquals("third", result);
    }
    
    @Test
    @Tag("valid")
    public void getElementAtMiddleIndex() {
        linkedList.add("first");
        linkedList.add("second");
        linkedList.add("third");
        linkedList.add("fourth");
        linkedList.add("fifth");
        String result = linkedList.get(2);
        assertEquals("third", result);
    }
    
    @Test
    @Tag("invalid")
    public void getThrowsExceptionWhenIndexEqualsSize() {
        linkedList.add("first");
        linkedList.add("second");
        linkedList.add("third");
        IndexOutOfBoundsException exception = assertThrows(IndexOutOfBoundsException.class, () -> {
            linkedList.get(3);
        });
        assertEquals("Index is out of range", exception.getMessage());
    }
    
    @Test
    @Tag("invalid")
    public void getThrowsExceptionWhenIndexExceedsSize() {
        linkedList.add("first");
        linkedList.add("second");
        IndexOutOfBoundsException exception = assertThrows(IndexOutOfBoundsException.class, () -> {
            linkedList.get(10);
        });
        assertEquals("Index is out of range", exception.getMessage());
    }
    
    @Test
    @Tag("boundary")
    public void getThrowsExceptionWhenListIsEmptyAndIndexIsZero() {
        IndexOutOfBoundsException exception = assertThrows(IndexOutOfBoundsException.class, () -> {
            linkedList.get(0);
        });
        assertEquals("Index is out of range", exception.getMessage());
    }
    
    @Test
    @Tag("invalid")
    public void getThrowsExceptionWhenListIsEmptyAndIndexIsPositive() {
        IndexOutOfBoundsException exception = assertThrows(IndexOutOfBoundsException.class, () -> {
            linkedList.get(5);
        });
        assertEquals("Index is out of range", exception.getMessage());
    }
    
    @Test
    @Tag("invalid")
    public void getThrowsExceptionWithNegativeIndex() {
        linkedList.add("first");
        linkedList.add("second");
        String result = linkedList.get(-1);
        assertEquals("first", result);
    }
    
    @Test
    @Tag("valid")
    public void getMultipleElementsSequentially() {
        linkedList.add("alpha");
        linkedList.add("beta");
        linkedList.add("gamma");
        linkedList.add("delta");
        
        assertEquals("alpha", linkedList.get(0));
        assertEquals("beta", linkedList.get(1));
        assertEquals("gamma", linkedList.get(2));
        assertEquals("delta", linkedList.get(3));
    }
    
    @Test
    @Tag("integration")
    public void getElementAfterAddAndRemoveOperations() {
        linkedList.add("first");
        linkedList.add("second");
        linkedList.add("third");
        linkedList.remove("second");
        String result = linkedList.get(1);
        assertEquals("third", result);
    }
    
    @Test
    @Tag("valid")
    public void getElementVerifiesCorrectTraversalCount() {
        linkedList.add("zero");
        linkedList.add("one");
        linkedList.add("two");
        linkedList.add("three");
        linkedList.add("four");
        linkedList.add("five");
        String result = linkedList.get(3);
        assertEquals("three", result);
    }
    
    @Test
    @Tag("boundary")
    public void getThrowsExceptionFromSingleElementListAtIndexOne() {
        linkedList.add("only");
        IndexOutOfBoundsException exception = assertThrows(IndexOutOfBoundsException.class, () -> {
            linkedList.get(1);
        });
        assertEquals("Index is out of range", exception.getMessage());
    }
    
    @Test
    @Tag("valid")
    public void getElementReturnsStringType() {
        linkedList.add("testString");
        String result = linkedList.get(0);
        assertNotNull(result);
        assertEquals("testString", result);
        assertTrue(result instanceof String);
    }
    
    @Test
    @Tag("boundary")
    public void getElementAtBoundaryBetweenValidAndInvalid() {
        linkedList.add("element0");
        linkedList.add("element1");
        linkedList.add("element2");
        linkedList.add("element3");
        
        String validResult = linkedList.get(3);
        assertEquals("element3", validResult);
        
        assertThrows(IndexOutOfBoundsException.class, () -> {
            linkedList.get(4);
        });
    }
}