/*
 * This source file was generated by the Gradle 'init' task
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test gradle-nov-20 using AI Type Claude AI and AI Model claude-haiku-4-5-20251001

ROOST_METHOD_HASH=remove_24f221c7ca
ROOST_METHOD_SIG_HASH=remove_c3106ffb54

Scenario 1: Remove Element from the Beginning of the LinkedList

Details:
  TestName: removeElementFromBeginning
  Description: This test verifies that the remove method successfully removes an element that is located at the head of the LinkedList. The method should return true, and the head pointer should be updated to point to the next node in the list.

Execution:
  Arrange: Create a LinkedList with multiple elements where the first element is the target element to be removed. Initialize the list with nodes containing data values such as "first", "second", and "third".
  Act: Invoke the remove method with the element "first" as the parameter.
  Assert: Verify that the method returns true, indicating successful removal. Confirm that the head of the LinkedList now points to the node containing "second".

Validation:
  This assertion validates that the unlink method correctly handles the case where the current node is the head node. The head reference should be updated to skip the removed node and point directly to its successor. This is critical for maintaining the integrity of the LinkedList structure when removing the first element.

*/

// ********RoostGPT********

package org.example.list;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;

@DisplayName("LinkedList Remove Method Tests")
class LinkedListRemoveTest {
    private LinkedList linkedList;
    @BeforeEach
    void setUp() {
        linkedList = new LinkedList();
    }
    @Test
    @Tag("valid")
    @DisplayName("Remove element from the beginning of the LinkedList")
    void removeElementFromBeginning() {
        // Arrange
        linkedList.add("first");
        linkedList.add("second");
        linkedList.add("third");
        // Act
        boolean result = linkedList.remove("first");
        // Assert
        assertTrue(result, "Remove should return true for existing element");
        assertEquals(2, linkedList.size(), "Size should be 2 after removal");
        assertEquals("second", linkedList.get(0), "Head should now point to 'second'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Remove element from the middle of the LinkedList")
    void removeElementFromMiddle() {
        // Arrange
        linkedList.add("first");
        linkedList.add("second");
        linkedList.add("third");
        // Act
        boolean result = linkedList.remove("second");
        // Assert
        assertTrue(result, "Remove should return true for existing element");
        assertEquals(2, linkedList.size(), "Size should be 2 after removal");
        assertEquals("first", linkedList.get(0), "First element should remain");
        assertEquals("third", linkedList.get(1), "Third element should be at index 1");
    }
    @Test
    @Tag("valid")
    @DisplayName("Remove element from the end of the LinkedList")
    void removeElementFromEnd() {
        // Arrange
        linkedList.add("first");
        linkedList.add("second");
        linkedList.add("third");
        // Act
        boolean result = linkedList.remove("third");
        // Assert
        assertTrue(result, "Remove should return true for existing element");
        assertEquals(2, linkedList.size(), "Size should be 2 after removal");
        assertEquals("first", linkedList.get(0), "First element should remain");
        assertEquals("second", linkedList.get(1), "Second element should remain");
    }
    @Test
    @Tag("valid")
    @DisplayName("Remove single element from LinkedList with one element")
    void removeSingleElement() {
        // Arrange
        linkedList.add("only");
        // Act
        boolean result = linkedList.remove("only");
        // Assert
        assertTrue(result, "Remove should return true");
        assertEquals(0, linkedList.size(), "Size should be 0 after removing single element");
    }
    @Test
    @Tag("invalid")
    @DisplayName("Remove non-existent element from LinkedList")
    void removeNonExistentElement() {
        // Arrange
        linkedList.add("first");
        linkedList.add("second");
        // Act
        boolean result = linkedList.remove("nonexistent");
        // Assert
        assertFalse(result, "Remove should return false for non-existent element");
        assertEquals(2, linkedList.size(), "Size should remain unchanged");
        assertEquals("first", linkedList.get(0), "List should remain unchanged");
    }
    @Test
    @Tag("boundary")
    @DisplayName("Remove from empty LinkedList")
    void removeFromEmptyList() {
        // Act
        boolean result = linkedList.remove("element");
        // Assert
        assertFalse(result, "Remove should return false on empty list");
        assertEquals(0, linkedList.size(), "Size should remain 0");
    }
    @Test
    @Tag("valid")
    @DisplayName("Remove first occurrence when duplicates exist")
    void removeFirstOccurrenceOfDuplicate() {
        // Arrange
        linkedList.add("duplicate");
        linkedList.add("unique");
        linkedList.add("duplicate");
        // Act
        boolean result = linkedList.remove("duplicate");
        // Assert
        assertTrue(result, "Remove should return true");
        assertEquals(2, linkedList.size(), "Size should be 2");
        assertEquals("unique", linkedList.get(0), "First element should be 'unique'");
        assertEquals("duplicate", linkedList.get(1), "Second element should be 'duplicate'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Remove multiple elements sequentially")
    void removeMultipleElementsSequentially() {
        // Arrange
        linkedList.add("first");
        linkedList.add("second");
        linkedList.add("third");
        linkedList.add("fourth");
        // Act
        boolean result1 = linkedList.remove("first");
        boolean result2 = linkedList.remove("third");
        boolean result3 = linkedList.remove("second");
        // Assert
        assertTrue(result1 && result2 && result3, "All removes should return true");
        assertEquals(1, linkedList.size(), "Size should be 1");
        assertEquals("fourth", linkedList.get(0), "Only 'fourth' should remain");
    }
    @ParameterizedTest
    @Tag("valid")
    @DisplayName("Remove various elements from LinkedList")
    @CsvSource({
        "first,second,third,first,true,2",
        "first,second,third,second,true,2",
        "first,second,third,third,true,2",
        "single,single,true,0"
    })
    void removeVariousElements(String... params) {
        // Arrange
        int paramCount = params.length;
        String elementToRemove = params[paramCount - 3];
        boolean expectedResult = Boolean.parseBoolean(params[paramCount - 2]);
        int expectedSize = Integer.parseInt(params[paramCount - 1]);
        for (int i = 0; i < paramCount - 3; i++) {
            linkedList.add(params[i]);
        }
        // Act
        boolean result = linkedList.remove(elementToRemove);
        // Assert
        assertEquals(expectedResult, result, "Remove result should match expected");
        assertEquals(expectedSize, linkedList.size(), "Size should match expected");
    }
    @Test
    @Tag("boundary")
    @DisplayName("Remove with null-like empty string")
    void removeEmptyString() {
        // Arrange
        linkedList.add("");
        linkedList.add("element");
        // Act
        boolean result = linkedList.remove("");
        // Assert
        assertTrue(result, "Remove should return true for empty string");
        assertEquals(1, linkedList.size(), "Size should be 1");
        assertEquals("element", linkedList.get(0), "Remaining element should be 'element'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Remove element with special characters")
    void removeElementWithSpecialCharacters() {
        // Arrange
        linkedList.add("element@123");
        linkedList.add("normal");
        linkedList.add("element@123");
        // Act
        boolean result = linkedList.remove("element@123");
        // Assert
        assertTrue(result, "Remove should return true");
        assertEquals(2, linkedList.size(), "Size should be 2");
        assertEquals("normal", linkedList.get(0), "First element should be 'normal'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Remove element with spaces")
    void removeElementWithSpaces() {
        // Arrange
        linkedList.add("element with spaces");
        linkedList.add("another");
        // Act
        boolean result = linkedList.remove("element with spaces");
        // Assert
        assertTrue(result, "Remove should return true");
        assertEquals(1, linkedList.size(), "Size should be 1");
        assertEquals("another", linkedList.get(0), "Remaining element should be 'another'");
    }
    @Test
    @Tag("integration")
    @DisplayName("Remove and add operations in sequence")
    void removeAndAddSequence() {
        // Arrange
        linkedList.add("first");
        linkedList.add("second");
        linkedList.add("third");
        // Act
        linkedList.remove("second");
        linkedList.add("fourth");
        boolean result = linkedList.remove("first");
        // Assert
        assertTrue(result, "Remove should return true");
        assertEquals(2, linkedList.size(), "Size should be 2");
        assertEquals("third", linkedList.get(0), "First element should be 'third'");
        assertEquals("fourth", linkedList.get(1), "Second element should be 'fourth'");
    }
    @Test
    @Tag("boundary")
    @DisplayName("Remove all elements one by one until empty")
    void removeAllElementsUntilEmpty() {
        // Arrange
        linkedList.add("first");
        linkedList.add("second");
        linkedList.add("third");
        // Act
        boolean result1 = linkedList.remove("first");
        boolean result2 = linkedList.remove("second");
        boolean result3 = linkedList.remove("third");
        boolean result4 = linkedList.remove("nonexistent");
        // Assert
        assertTrue(result1 && result2 && result3, "All valid removes should return true");
        assertFalse(result4, "Remove from empty list should return false");
        assertEquals(0, linkedList.size(), "Size should be 0");
    }
    @Test
    @Tag("valid")
    @DisplayName("Remove element with case sensitivity")
    void removeElementCaseSensitive() {
        // Arrange
        linkedList.add("Element");
        linkedList.add("element");
        // Act
        boolean result = linkedList.remove("element");
        // Assert
        assertTrue(result, "Remove should return true for exact match");
        assertEquals(1, linkedList.size(), "Size should be 1");
        assertEquals("Element", linkedList.get(0), "Capitalized element should remain");
    }
}