/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.list;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.example.list.LinkedList;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;

public class LinkedListAddTest {
    @Test
    @Tag("valid")
    public void testAddElementToEmptyList() {
        LinkedList list = new LinkedList();
        list.add("A");
        assertEquals((String) "A", (String) list.get(0));
        assertEquals((int) 1, (int) list.size());
    }
    @Test
    @Tag("valid")
    public void testAddElementToNonEmptyList() {
        LinkedList list = new LinkedList();
        list.add("A");
        list.add("B");
        assertEquals((String) "A", (String) list.get(0));
        assertEquals((String) "B", (String) list.get(1));
        assertEquals((int) 2, (int) list.size());
    }
    @Test
    @Tag("valid")
    public void testAddMultipleElementsSequentially() {
        LinkedList list = new LinkedList();
        list.add("A");
        list.add("B");
        list.add("C");
        assertEquals((String) "A", (String) list.get(0));
        assertEquals((String) "B", (String) list.get(1));
        assertEquals((String) "C", (String) list.get(2));
        assertEquals((int) 3, (int) list.size());
    }
    @Test
    @Tag("boundary")
    public void testAddNullElement() {
        LinkedList list = new LinkedList();
        list.add(null);
        assertNull((String) list.get(0));
        assertEquals((int) 1, (int) list.size());
    }
    @Test
    @Tag("valid")
    public void testAddDuplicateElements() {
        LinkedList list = new LinkedList();
        list.add("A");
        list.add("A");
        assertEquals((String) "A", (String) list.get(0));
        assertEquals((String) "A", (String) list.get(1));
        assertEquals((int) 2, (int) list.size());
    }
    @Test
    @Tag("integration")
    public void testAddAfterListIsCleared() {
        LinkedList list = new LinkedList();
        list.add("A");
        list.add("B");
        list.remove("A");
        list.remove("B");
        assertEquals((int) 0, (int) list.size());
        list.add("C");
        assertEquals((String) "C", (String) list.get(0));
        assertEquals((int) 1, (int) list.size());
    }
    @Test
    @Tag("boundary")
    public void testAddVeryLongStringElement() {
        LinkedList list = new LinkedList();
        String longString = "A".repeat(10000); // TODO: Change string length if needed
        list.add(longString);
        assertEquals((String) longString, (String) list.get(0));
        assertEquals((int) 1, (int) list.size());
    }
    @Test
    @Tag("valid")
    public void testAddElementsWithSpecialCharacters() {
        LinkedList list = new LinkedList();
        String specialCharString = "A@!#";
        list.add(specialCharString);
        assertEquals((String) specialCharString, (String) list.get(0));
        assertEquals((int) 1, (int) list.size());
    }
    @Test
    @Tag("boundary")
    public void testAddElementToListWithNullDataNode() {
        LinkedList list = new LinkedList();
        list.add(null);
        list.add("A");
        assertNull((String) list.get(0));
        assertEquals((String) "A", (String) list.get(1));
        assertEquals((int) 2, (int) list.size());
    }
    @Test
    @Tag("valid")
    public void testAddMultipleElementsAndCheckSize() {
        LinkedList list = new LinkedList();
        list.add("A");
        list.add("B");
        list.add("C");
        assertEquals((int) 3, (int) list.size());
    }
}