

// ********RoostGPT********
/*
Test generated by RoostGPT for test nov-26-gradle using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=getName_3a12ffc596
ROOST_METHOD_SIG_HASH=getName_8400ac6fb7

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/nov-26-gradle/7ef80b58-12be-4a83-a9cb-8829bc0fa249/source/gradle-app/demo/src/test/java/com/example/demo/domain/CustomerRepositoryTest.java
Tests:
    "@Test
void testSaveAndFind() {
    Customer c = new Customer("Alice", "alice@local");
    Customer saved = customerRepository.save(c);
    assertThat(saved.getId()).isNotNull();
    Customer found = customerRepository.findById(saved.getId()).orElseThrow();
    assertThat(found.getName()).isEqualTo("Alice");
}
"

File Path: /var/tmp/Roost/RoostGPT/nov-26-gradle/7ef80b58-12be-4a83-a9cb-8829bc0fa249/source/gradle-app/demo/src/test/java/com/example/demo/service/CustomerServiceTest.java
Tests:
    "@Test
void testGetCustomerById() {
    Customer c = new Customer("Bob", "b@x.com");
    when(customerRepository.findById(1L)).thenReturn(Optional.of(c));
    Optional<Customer> result = customerService.getCustomerById(1L);
    assertThat(result).isPresent();
    assertThat(result.get().getName()).isEqualTo("Bob");
}
"
    "@Test
void testCreateCustomer() {
    Customer c = new Customer("Charlie", "c@x.com");
    when(customerRepository.save(any(Customer.class))).thenReturn(c);
    Customer result = customerService.createCustomer(c);
    assertThat(result.getName()).isEqualTo("Charlie");
}
"Scenario 1: Retrieve Name When Name Is Set Via Constructor

Details:
  TestName: getNameReturnsNameSetViaConstructor
  Description: Verify that the getName() method correctly returns the name value that was set through the constructor during object instantiation.

Execution:
  Arrange: Create a new Customer object using the constructor with a valid name string "John Doe" and an email.
  Act: Invoke the getName() method on the Customer instance.
  Assert: Assert that the returned value equals "John Doe".

Validation:
  The assertion verifies that the getName() method correctly retrieves the name field value that was initialized through the constructor. This is fundamental to ensure the basic getter functionality works as expected and that the constructor properly assigns the name parameter to the internal field.

---

Scenario 2: Retrieve Name When Name Is Set Via Setter Method

Details:
  TestName: getNameReturnsNameSetViaSetter
  Description: Verify that the getName() method correctly returns the name value after it has been modified using the setName() method.

Execution:
  Arrange: Create a new Customer object using the default constructor, then use setName() to set the name to "Jane Smith".
  Act: Invoke the getName() method on the Customer instance.
  Assert: Assert that the returned value equals "Jane Smith".

Validation:
  The assertion confirms that getName() properly reflects changes made through the setName() method. This validates the interaction between the setter and getter methods, ensuring data consistency when the name field is modified after object creation.

---

Scenario 3: Retrieve Name When Name Is Null

Details:
  TestName: getNameReturnsNullWhenNameNotSet
  Description: Verify that the getName() method returns null when a Customer object is created using the default constructor without setting a name.

Execution:
  Arrange: Create a new Customer object using the default no-argument constructor without setting any name value.
  Act: Invoke the getName() method on the Customer instance.
  Assert: Assert that the returned value is null.

Validation:
  The assertion verifies that getName() correctly returns null when the name field has not been initialized. This is important for handling edge cases where Customer objects may exist without a name, and ensures the application can properly handle null values.

---

Scenario 4: Retrieve Name When Name Is Empty String

Details:
  TestName: getNameReturnsEmptyStringWhenSetToEmpty
  Description: Verify that the getName() method correctly returns an empty string when the name is explicitly set to an empty string value.

Execution:
  Arrange: Create a new Customer object using the constructor with an empty string "" as the name parameter and a valid email.
  Act: Invoke the getName() method on the Customer instance.
  Assert: Assert that the returned value equals "" (empty string).

Validation:
  The assertion confirms that getName() accurately returns an empty string when that is the assigned value. This distinguishes between a null name (never set) and an explicitly empty name, which may have different business implications in the application.

---

Scenario 5: Retrieve Name With Special Characters

Details:
  TestName: getNameReturnsNameWithSpecialCharacters
  Description: Verify that the getName() method correctly returns a name containing special characters, spaces, and unicode characters.

Execution:
  Arrange: Create a new Customer object using the constructor with a name containing special characters such as "José María O'Connor-Smith".
  Act: Invoke the getName() method on the Customer instance.
  Assert: Assert that the returned value equals "José María O'Connor-Smith".

Validation:
  The assertion verifies that getName() handles names with accented characters, apostrophes, hyphens, and spaces correctly. This is crucial for internationalization support and ensuring the application can handle diverse customer names from various cultural backgrounds.

---

Scenario 6: Retrieve Name After Multiple Updates

Details:
  TestName: getNameReturnsLatestValueAfterMultipleUpdates
  Description: Verify that the getName() method returns the most recently set name value after the name has been updated multiple times.

Execution:
  Arrange: Create a new Customer object with initial name "First Name", then call setName() with "Second Name", and finally call setName() with "Final Name".
  Act: Invoke the getName() method on the Customer instance.
  Assert: Assert that the returned value equals "Final Name".

Validation:
  The assertion confirms that getName() always returns the current state of the name field, reflecting the most recent update. This validates that the setter properly overwrites previous values and the getter retrieves the latest state.

---

Scenario 7: Retrieve Name With Whitespace Only

Details:
  TestName: getNameReturnsWhitespaceWhenSetToWhitespace
  Description: Verify that the getName() method correctly returns a string containing only whitespace characters when such a value is set.

Execution:
  Arrange: Create a new Customer object using the constructor with a name consisting of only spaces "   " and a valid email.
  Act: Invoke the getName() method on the Customer instance.
  Assert: Assert that the returned value equals "   " (three spaces).

Validation:
  The assertion verifies that getName() returns the exact whitespace string that was set, without any trimming or modification. This tests the raw data retrieval behavior of the getter method and may be relevant for validation logic elsewhere in the application.

*/

// ********RoostGPT********

package com.example.demo.domain;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;

class CustomerGetNameTest {
    private Customer customer;
    @BeforeEach
    void setUp() {
        customer = new Customer();
    }
    @Test
    @Tag("valid")
    @DisplayName("Verify that getName() returns the name set via constructor")
    void getNameReturnsNameSetViaConstructor() {
        // Arrange
        Customer customerWithName = new Customer("John Doe", "john.doe@example.com");
        // Act
        String result = customerWithName.getName();
        // Assert
        assertEquals("John Doe", result);
    }
    @Test
    @Tag("valid")
    @DisplayName("Verify that getName() returns the name set via setter method")
    void getNameReturnsNameSetViaSetter() {
        // Arrange
        customer.setName("Jane Smith");
        // Act
        String result = customer.getName();
        // Assert
        assertEquals("Jane Smith", result);
    }
    @Test
    @Tag("boundary")
    @DisplayName("Verify that getName() returns null when name is not set")
    void getNameReturnsNullWhenNameNotSet() {
        // Arrange
        // Using default constructor, name is not set
        // Act
        String result = customer.getName();
        // Assert
        assertNull(result);
    }
    @Test
    @Tag("boundary")
    @DisplayName("Verify that getName() returns empty string when set to empty")
    void getNameReturnsEmptyStringWhenSetToEmpty() {
        // Arrange
        Customer customerWithEmptyName = new Customer("", "test@example.com");
        // Act
        String result = customerWithEmptyName.getName();
        // Assert
        assertEquals("", result);
    }
    @Test
    @Tag("valid")
    @DisplayName("Verify that getName() returns name with special characters")
    void getNameReturnsNameWithSpecialCharacters() {
        // Arrange
        Customer customerWithSpecialName = new Customer("José María O'Connor-Smith", "jose@example.com");
        // Act
        String result = customerWithSpecialName.getName();
        // Assert
        assertEquals("José María O'Connor-Smith", result);
    }
    @Test
    @Tag("valid")
    @DisplayName("Verify that getName() returns the latest value after multiple updates")
    void getNameReturnsLatestValueAfterMultipleUpdates() {
        // Arrange
        Customer customerWithUpdates = new Customer("First Name", "test@example.com");
        customerWithUpdates.setName("Second Name");
        customerWithUpdates.setName("Final Name");
        // Act
        String result = customerWithUpdates.getName();
        // Assert
        assertEquals("Final Name", result);
    }
    @Test
    @Tag("boundary")
    @DisplayName("Verify that getName() returns whitespace when set to whitespace only")
    void getNameReturnsWhitespaceWhenSetToWhitespace() {
        // Arrange
        Customer customerWithWhitespaceName = new Customer("   ", "test@example.com");
        // Act
        String result = customerWithWhitespaceName.getName();
        // Assert
        assertEquals("   ", result);
    }
}